---
- name: Bundle - gem update --system
  shell: "gem update --system"

- name: Bundle - Ensure bundler is installed.
  gem: name="bundler" state=present user_install=no

- name: Bundle - Ensure bundler is updated.
  shell: "bundle update"
  args:
    chdir: "{{ redmine_home }}"

- name: Bundle - Ensure bundled gems are installed.
  bundler: state=present chdir="{{ redmine_home }}"

- name: Bundle - Ensure required gems are installed.
  gem: name="activerecord-mysql2-adapter" state=present

- name: Bundle - Generate secret token
  shell: "bundle exec rake generate_secret_token"
  args:
    chdir: "{{ redmine_home }}"

- name: Bundle - Migrate database
  shell: "RAILS_ENV=production bundle exec rake db:migrate"
  args:
    chdir: "{{ redmine_home }}"

- name: Bundle - Default data
  shell: "RAILS_ENV=production REDMINE_LANG=en bundle exec rake redmine:load_default_data"
  args:
    chdir: "{{ redmine_home }}"
  when: redmine_load_default_data is defined and redmine_load_default_data