---
- name: Git - Ensure prerequisites packages are installed.
  apt: package="{{ item }}" state=installed
  with_items: redmine_git_packages

- name: Git - Clone repository.
  git:
    repo: "{{ redmine_git_repo }}"
    dest: "{{ redmine_install_dir }}"
    version: "{{ redmine_git_version }}"
    accept_hostkey: yes

- name: Git - Ensure database.yml is set.
  template:
    src: database.yml.j2
    dest: "{{ redmine_install_dir }}/config/database.yml"

- include: 'bundle.yml'