---
- include_vars: "{{ redmine_sgbd }}.yml"
  no_log: True

- include_tasks: "{{ redmine_sgbd }}.yml"
  when: redmine_sgbd != 'sqlite3'

- include_tasks: "{{ redmine_install }}.yml"

- name: Ensure redmine group is present.
  group:
    name: "{{ redmine_group }}"
    state: present

- name: Ensure redmine user is present.
  user:
    name: "{{ redmine_user }}"
    group: "{{ redmine_group }}"
    home: "{{ redmine_home }}"
    skeleton: True
    state: present

- include_tasks: "{{ redmine_http_service }}.yml"
  when: redmine_http_service is defined

- name: Ensure log directory is linked.
  file:
    src: "/usr/share/redmine/log"
    dest: "/var/log/redmine"
    state: link

- name: Ensure directories are writable by the group.
  file:
    path: "/usr/share/redmine/{{ item }}"
    state: directory
    mode: g=rwX
    recurse: yes
  with_items: "{{ redmine_writable_dirs }}"

- name: Ensure redmine ownership.
  file:
    path: "{{ redmine_home }}"
    owner: "{{ redmine_user }}"
    group: "{{ redmine_group }}"
    recurse: yes
