---
- include_vars: "{{ redmine_sgbd }}.yml"
  no_log: True

- include: "{{ redmine_sgbd }}.yml"
  when: redmine_sgbd != 'sqlite3'

- include: "{{ redmine_install }}.yml"

- name: Ensure redmine group is present.
  group: name="{{ redmine_group }}" state=present

- name: Ensure redmine user is present.
  user:
    name: "{{ redmine_user }}"
    group: "{{ redmine_group }}"
    home: "{{ redmine_home }}"
    state: present